# Generated by Django 3.0.3 on 2020-03-05 14:05

from django.db import migrations, models
import swlibs.json_api.django
import tests.swlibs.json_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DummyModel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('related', swlibs.json_api.django.RelatedJSONAPIField(
                    json_api_model=tests.swlibs.json_api.models.DummyRelated)),
                ('other', swlibs.json_api.django.RelatedJSONAPIField(
                    json_api_model=tests.swlibs.json_api.models.DummyRelated, null=True)),
            ],
        ),
    ]
